
title: sample API schema
description: sample API schema
db:
    user: root
    passwd: 
    addr: 127.0.0.1:3306
    dbname: mig

definitions:
    ok:
        type: boolean
        db_type: bool
        description: succeesed check
        example: true
    
    user_id:
        type: string
        db_type: int(11)
        description: user id
        example: okpk
        readOnly: true
        unique: true

    screen_name:
        type: string
        db_type: varchar(255)
        description: user secreen name
        example: hei

    password:
        type: string
        db_type: varchar(255)
        description: user password
        example: meta-closure

    title:
        type: string
        description: post title
        example: TITLE
    body:
        type: string
        description: post body
        example: this is body
    post_id:
        type: integer
        description: post id
        example: 1011
        unique: true
    page:
        type: integer
        description: page
        example: 1

    user:
        type: object
        title: User
        description: User
        table: 
            name: users
            primary_key:
                name: user_id
                key:
                    - user_id
        properties:
            user_id:
                column: 
                    name: user_id
                    type: int
                    not_null: true
                    auto_increment: true
                $ref: '#/definitions/user_id'
            screen_name:
                column:
                    name: screen_name
                    type: varchar(255)
                $ref: '#/definitions/screen_name'
    post:
        type: object
        title: posts
        description: post
        table:
            name: posts
            primary_key: 
                name: post_id
                key:
                    - post_id
        properties:
            post_id:
                column:
                    not_null: true
                    name: post_id
                    type: int
                    auto_increment: true
                $ref: '#/definitions/post_id'
            
            title:
                column:
                    name: title
                    type: varchar(255)
                $ref: '#/definitions/title'
            body:
                column:
                    name: body
                    type: varchar(255)
                $ref: '#/definitions/body'
    
    posts:
        type: array
        title: posts
        description: posts
        items:
            $ref: '#/definitions/post'
                    

href: https://sample-app
pathStart: /v1
    
links:
    - title: CREATE user
      description: create user
      rel: create
      href: /users
      method: POST
      schema:
          type: object
          properties:
              user_id:
                  $ref: '#/definitions/user_id'
              screen_name:
                  $ref: '#/definitions/screen_name'
              password:
                  $ref: '#/definitions/password'
          required:
              - user_id
              - screen_name
              
      targetSchema:
          $ref: '#/definitions/user'
